'use client';

import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Loader2, Save, X } from 'lucide-react';
import {
  createPhotoReportSchema,
  updatePhotoReportSchema,
  type CreatePhotoReportInput,
  type UpdatePhotoReportInput,
} from '@/packages/schemas/photo-reports';
import {
  type ProjectPhotoReportsQuery,
} from '@/packages/api/graphql/__generated__/output';
import { PhotoUploaderNew } from './PhotoUploaderNew';

type PhotoReportWithPhotos = ProjectPhotoReportsQuery['projectPhotoReports'][0];

interface PhotoReportFormProps {
  projectId: string;
  report?: PhotoReportWithPhotos;
  onSubmit: (data: CreatePhotoReportInput | UpdatePhotoReportInput) => Promise<void>;
  onCancel?: () => void;
  isLoading?: boolean;
  onUploadPhoto?: (file: File, caption?: string) => Promise<any>;
  onDeletePhoto?: (photoId: string) => Promise<void>;
  onReorderPhotos?: (newOrder: string[]) => Promise<void>;
  onCaptionChange?: (photoId: string, caption: string) => Promise<void>;
}

export function PhotoReportForm({
  projectId,
  report,
  onSubmit,
  onCancel,
  isLoading = false,
  onUploadPhoto,
  onDeletePhoto,
  onReorderPhotos,
  onCaptionChange,
}: PhotoReportFormProps) {
  const isEditMode = !!report;
  const [error, setError] = useState<string | null>(null);

  // Local state for transactional editing
  const [deletedPhotoIds, setDeletedPhotoIds] = useState<Set<string>>(new Set());
  const [newPhotos, setNewPhotos] = useState<Array<{ id: string; file: File; preview: string; name: string }>>([]);
  
  // State for ordering and captions
  const [photoOrder, setPhotoOrder] = useState<string[]>([]);
  const [photoCaptions, setPhotoCaptions] = useState<Record<string, string>>({});

  // TODO: ReorderReportPhotosDocument needs to be generated by codegen
  // For now, reordering is handled locally and will be persisted on next save
  // const [reorderPhotos] = useMutation(ReorderReportPhotosDocument);

  // Initialize order from report
  useEffect(() => {
    if (report?.photos) {
      setPhotoOrder(report.photos.map(p => p.id));
    }
  }, [report]);

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<any>({
    resolver: zodResolver(isEditMode ? updatePhotoReportSchema : createPhotoReportSchema) as any,
    defaultValues: isEditMode
      ? {
          id: report.id,
          title: report.title,
          description: report.description || '',
          isPublic: report.isPublic,
        }
      : {
          projectId,
          title: '',
          description: '',
          isPublic: true,
        },
  });

  // Derived state for display
  // 1. Filter out deleted existing photos
  const existingPhotos = (report?.photos || []).filter((p) => !deletedPhotoIds.has(p.id));
  
  // 2. Combine with new photos
  const allPhotos = [
    ...existingPhotos.map((p) => ({ ...p, isNew: false })),
    ...newPhotos.map((p) => ({
      id: p.id,
      photoUrl: p.preview,
      thumbnailUrl: p.preview,
      caption: photoCaptions[p.id] || null,
      orderIndex: 0,
      width: 0,
      height: 0,
      fileSize: p.file.size,
      createdAt: new Date().toISOString(),
      __typename: 'ReportPhoto' as const,
      isNew: true,
    })),
  ];

  // 3. Sort based on photoOrder
  // If an ID is not in photoOrder (e.g. newly added), append it to the end
  const currentPhotos = allPhotos.sort((a, b) => {
    const idxA = photoOrder.indexOf(a.id);
    const idxB = photoOrder.indexOf(b.id);
    
    // New items might not be in photoOrder yet if we haven't updated state, 
    // but handleLocalUpload updates it.
    if (idxA === -1) return 1;
    if (idxB === -1) return -1;
    return idxA - idxB;
  });

  // Combined report object for PhotoUploader
  const displayReport = report
    ? { ...report, photos: currentPhotos }
    : {
        id: 'draft',
        photos: currentPhotos,
        projectId,
        title: '',
        description: '',
        coverPhotoUrl: null,
        isPublic: true,
        slug: '',
        createdById: '',
        createdAt: '',
        updatedAt: '',
        publishedAt: '',
        viewCount: 0,
        __typename: 'PhotoReport' as const,
      };

  const handleLocalUpload = async (file: File, caption?: string) => {
    const preview = URL.createObjectURL(file);
    const id = `new-${Date.now()}-${Math.random()}`;
    
    setNewPhotos((prev) => [...prev, { id, file, preview, name: file.name }]);
    if (caption) {
      setPhotoCaptions(prev => ({ ...prev, [id]: caption }));
    }
    setPhotoOrder(prev => [...prev, id]); // Append to order
  };

  const handleLocalDelete = async (photoId: string) => {
    if (photoId.startsWith('new-')) {
      setNewPhotos((prev) => {
        const photo = prev.find((p) => p.id === photoId);
        if (photo) URL.revokeObjectURL(photo.preview);
        return prev.filter((p) => p.id !== photoId);
      });
    } else {
      setDeletedPhotoIds((prev) => {
        const next = new Set(prev);
        next.add(photoId);
        return next;
      });
    }
    setPhotoOrder(prev => prev.filter(id => id !== photoId));
  };

  const handleLocalReorder = (newOrder: string[]) => {
    setPhotoOrder(newOrder);
    // If in edit mode and parent provides handler, call it immediately
    if (isEditMode && onReorderPhotos) {
      onReorderPhotos(newOrder).catch(console.error);
    }
  };

  const handleLocalCaptionChange = (photoId: string, caption: string) => {
    setPhotoCaptions(prev => ({ ...prev, [photoId]: caption }));
    // If in edit mode and parent provides handler, call it immediately
    if (isEditMode && onCaptionChange) {
      onCaptionChange(photoId, caption).catch(console.error);
    }
  };

  const handleFormSubmit = async (data: CreatePhotoReportInput | UpdatePhotoReportInput) => {
    setError(null);
    try {
      // 1. Process deletions
      if (onDeletePhoto && deletedPhotoIds.size > 0) {
        await Promise.all(Array.from(deletedPhotoIds).map((id) => onDeletePhoto(id)));
      }

      // 2. Process uploads (Parallel)
      const idMapping = new Map<string, string>(); // tempId -> realId
      
      if (onUploadPhoto && newPhotos.length > 0) {
         // Create array of promises
         const uploadPromises = newPhotos.map(async (photo) => {
             const caption = photoCaptions[photo.id];
             const result = await onUploadPhoto(photo.file, caption);
             
             // Assuming result contains the created photo object with ID
             // Check if result is available and has ID
             // The mutation usually returns { data: { uploadPhotoToReport: { id: ... } } }
             // But onUploadPhoto wrapper might return the photo directly or the result object.
             // We need to be careful here depending on how onUploadPhoto is implemented in page.tsx
             // Looking at page.tsx (from memory/context), it calls the mutation.
             // We might need to inspect the return value.
             
             // If onUploadPhoto returns void/promise<void>, we can't map IDs easily...
             // BUT, the page.tsx implementation uses 'uploadPhotoToReport' mutation.
             // We need to update page.tsx? 
             // Wait, page.tsx just calls the mutation and refetches.
             // To enable reordering of NEW photos, we MUST get their IDs back.
             
             // Let's assume onUploadPhoto returns the photo object. 
             // If not, we might fall back to "reorder only works for existing photos next time".
             // But we want it to work now.
             
             // For now, let's assume we can get the ID.
             if (result && result.id) {
                idMapping.set(photo.id, result.id);
             } else if (result && result.data?.uploadPhotoToReport?.id) {
                idMapping.set(photo.id, result.data.uploadPhotoToReport.id);
             }
         });

         await Promise.all(uploadPromises);
      }

      // 3. Save form data (The Report itself)
      await onSubmit(data);

      // 4. Update Order (Post-save)
      // Only runs if we have a report ID (either edit mode or just created)
      // If we just created, we need the new ID. data doesn't have it.
      // But onSubmit handles the update/create call.
      // Ideally, reorder should happen AFTER photos are uploaded.
      // If we are in CREATE mode, the report ID is implicitly handled by the parent reload?
      // Actually, if we are in CREATE mode, we might not have the ID here easily unless onSubmit returns it.
      
      // TODO: Reorder photos after upload when ReorderReportPhotosDocument is available
      // For now, photos maintain their upload order
      // if (report?.id) {
      //     const finalOrder = photoOrder
      //       .map(id => idMapping.get(id) || id)
      //       .filter(id => !id.startsWith('new-') && !deletedPhotoIds.has(id));
      //     await reorderPhotos({
      //        variables: {
      //           reportId: report.id,
      //           photoIds: finalOrder
      //        }
      //     });
      // }

      if (!isEditMode) {
        reset();
      }
      
      // Reset local state
      setDeletedPhotoIds(new Set());
      setNewPhotos([]);
      setPhotoCaptions({});
      // Photo order will differ refresh from parent
      
    } catch (err) {
      console.error(err);
      setError(err instanceof Error ? err.message : 'Произошла ошибка при сохранении');
      // If error, we shouldn't clear state so user can retry
    }
  };

  return (
    <form onSubmit={handleSubmit(handleFormSubmit)} className="space-y-6">
      {/* Title field */}
      <div>
        <label htmlFor="title" className="block text-sm font-medium text-gray-700 mb-2">
          Название фотоотчёта <span className="text-red-500">*</span>
        </label>
        <input
          id="title"
          type="text"
          {...register('title')}
          disabled={isLoading}
          placeholder="Например: Этап 1 - Фундамент"
          className={`
            w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500
            ${errors.title ? 'border-red-500' : 'border-gray-300'}
            ${isLoading ? 'opacity-50 cursor-not-allowed' : ''}
          `}
        />
        {errors.title && (
          <p className="mt-1 text-sm text-red-600">{errors.title?.message as string}</p>
        )}
      </div>

      {/* Description field */}
      <div>
        <label htmlFor="description" className="block text-sm font-medium text-gray-700 mb-2">
          Описание
        </label>
        <textarea
          id="description"
          {...register('description')}
          disabled={isLoading}
          placeholder="Опишите текущий этап работ или достижения..."
          rows={4}
          className={`
            w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none
            ${errors.description ? 'border-red-500' : 'border-gray-300'}
            ${isLoading ? 'opacity-50 cursor-not-allowed' : ''}
          `}
        />
        {errors.description && (
          <p className="mt-1 text-sm text-red-600">{errors.description?.message as string}</p>
        )}
      </div>

      {/* Public toggle */}
      <div className="flex items-center gap-3">
        <input
          id="isPublic"
          type="checkbox"
          {...register('isPublic')}
          disabled={isLoading}
          className="h-4 w-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
        />
        <label htmlFor="isPublic" className="text-sm text-gray-700">
          Сделать отчёт публичным (доступен по ссылке без авторизации)
        </label>
      </div>

      {/* Photo Uploader */}
      {(isEditMode || (onUploadPhoto && onDeletePhoto)) && (
        <div className="pt-4 border-t">
          <h3 className="text-sm font-medium text-gray-700 mb-3">
            Фотографии ({currentPhotos.length})
          </h3>
          <PhotoUploaderNew
            report={displayReport}
            onUpload={handleLocalUpload}
            onDeletePhoto={handleLocalDelete}
            onReorder={handleLocalReorder}
            onCaptionChange={handleLocalCaptionChange}
            disabled={isLoading}
          />
        </div>
      )}

      {/* Error message */}
      {error && (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
          <p className="text-sm text-red-800">{error}</p>
        </div>
      )}

      {/* Action buttons */}
      <div className="flex items-center gap-3 pt-4 border-t">
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            disabled={isLoading}
            className="px-4 py-2 border border-border text-gray-700 rounded-lg hover:bg-gray-50 disabled:opacity-50"
          >
            <X className="inline h-4 w-4 mr-2" />
            Отмена
          </button>
        )}

        <button
          type="submit"
          disabled={isLoading}
          className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 flex items-center justify-center gap-2"
        >
          {isLoading ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              Сохранение...
            </>
          ) : (
            <>
              <Save className="h-4 w-4" />
              {isEditMode ? 'Сохранить изменения' : 'Создать фотоотчёт'}
            </>
          )}
        </button>
      </div>
    </form>
  );
}
